import type { DistrictProfile } from "./types"

export const tamilNaduDistricts: DistrictProfile[] = [
  {
    name: "Chennai",
    population: 4646732,
    ruralPopulation: 185000,
    totalHouseholds: 1200000,
    description: "Capital city and major metropolitan area of Tamil Nadu",
    keyIndustries: ["IT Services", "Automobile", "Healthcare", "Port Operations"],
    challenges: ["Limited rural areas", "Urban migration", "Infrastructure strain"],
  },
  {
    name: "Coimbatore",
    population: 3458045,
    ruralPopulation: 1200000,
    totalHouseholds: 850000,
    description: "Major industrial and textile hub known as the Manchester of South India",
    keyIndustries: ["Textiles", "Engineering", "Agriculture", "IT"],
    challenges: ["Water scarcity", "Industrial pollution", "Seasonal employment"],
  },
  {
    name: "Madurai",
    population: 3038252,
    ruralPopulation: 1800000,
    totalHouseholds: 750000,
    description: "Historic temple city and cultural center of Tamil Nadu",
    keyIndustries: ["Agriculture", "Handloom", "Tourism", "Small Scale Industries"],
    challenges: ["Agricultural dependency", "Drought conditions", "Rural unemployment"],
  },
  {
    name: "Tiruchirappalli",
    population: 2722290,
    ruralPopulation: 1600000,
    totalHouseholds: 680000,
    description: "Central Tamil Nadu district known for engineering and education",
    keyIndustries: ["Engineering", "Agriculture", "Education", "Heavy Industries"],
    challenges: ["Seasonal agriculture", "Water management", "Rural-urban divide"],
  },
  {
    name: "Salem",
    population: 3482056,
    ruralPopulation: 2100000,
    totalHouseholds: 870000,
    description: "Steel city and major agricultural center",
    keyIndustries: ["Steel", "Textiles", "Agriculture", "Sago"],
    challenges: ["Industrial pollution", "Agricultural distress", "Employment generation"],
  },
  {
    name: "Tirunelveli",
    population: 3077233,
    ruralPopulation: 2200000,
    totalHouseholds: 770000,
    description: "Southernmost district known for agriculture and traditional industries",
    keyIndustries: ["Agriculture", "Handloom", "Small Industries", "Tourism"],
    challenges: ["Monsoon dependency", "Traditional industry decline", "Youth migration"],
  },
  {
    name: "Vellore",
    population: 3936331,
    ruralPopulation: 2800000,
    totalHouseholds: 980000,
    description: "Leather and healthcare hub with significant rural population",
    keyIndustries: ["Leather", "Healthcare", "Agriculture", "Education"],
    challenges: ["Groundwater depletion", "Leather industry pollution", "Rural poverty"],
  },
  {
    name: "Erode",
    population: 2251744,
    ruralPopulation: 1400000,
    totalHouseholds: 560000,
    description: "Textile and turmeric trading center",
    keyIndustries: ["Textiles", "Agriculture", "Turmeric Trade", "Handloom"],
    challenges: ["Water scarcity", "Textile industry fluctuations", "Agricultural sustainability"],
  },
  {
    name: "Tirupur",
    population: 2479052,
    ruralPopulation: 800000,
    totalHouseholds: 620000,
    description: "Knitwear capital of India",
    keyIndustries: ["Knitwear", "Textiles", "Garment Export", "Dyeing"],
    challenges: ["Water pollution", "Seasonal employment", "Export market dependency"],
  },
  {
    name: "Dindigul",
    population: 2159775,
    ruralPopulation: 1600000,
    totalHouseholds: 540000,
    description: "Lock and leather goods manufacturing center",
    keyIndustries: ["Lock Manufacturing", "Leather", "Agriculture", "Tanneries"],
    challenges: ["Traditional industry modernization", "Agricultural productivity", "Skill development"],
  },
  {
    name: "Thanjavur",
    population: 2405890,
    ruralPopulation: 1900000,
    totalHouseholds: 600000,
    description: "Rice bowl of Tamil Nadu and cultural heritage center",
    keyIndustries: ["Agriculture", "Rice Milling", "Handicrafts", "Tourism"],
    challenges: ["Monsoon dependency", "Agricultural modernization", "Cultural preservation"],
  },
  {
    name: "Nagapattinam",
    population: 1616450,
    ruralPopulation: 1400000,
    totalHouseholds: 400000,
    description: "Coastal district known for agriculture and fishing",
    keyIndustries: ["Agriculture", "Fishing", "Salt Production", "Port Activities"],
    challenges: ["Cyclone vulnerability", "Sea level rise", "Fishing industry sustainability"],
  },
  {
    name: "Cuddalore",
    population: 2605914,
    ruralPopulation: 1800000,
    totalHouseholds: 650000,
    description: "Industrial and port district on the east coast",
    keyIndustries: ["Petrochemicals", "Port Operations", "Agriculture", "Fishing"],
    challenges: ["Industrial pollution", "Coastal erosion", "Environmental degradation"],
  },
  {
    name: "Villupuram",
    population: 3458873,
    ruralPopulation: 2800000,
    totalHouseholds: 860000,
    description: "Predominantly agricultural district with high rural population",
    keyIndustries: ["Agriculture", "Rice Milling", "Handloom", "Small Industries"],
    challenges: ["Agricultural dependency", "Rural unemployment", "Infrastructure development"],
  },
  {
    name: "Kanchipuram",
    population: 3998252,
    ruralPopulation: 2200000,
    totalHouseholds: 1000000,
    description: "Silk saree weaving center and temple town",
    keyIndustries: ["Silk Weaving", "Agriculture", "Tourism", "Handloom"],
    challenges: ["Traditional industry competition", "Urbanization pressure", "Skill preservation"],
  },
  {
    name: "Tiruvallur",
    population: 3728104,
    ruralPopulation: 2000000,
    totalHouseholds: 930000,
    description: "Rapidly developing district near Chennai",
    keyIndustries: ["Agriculture", "Small Industries", "IT", "Manufacturing"],
    challenges: ["Urban expansion", "Agricultural land conversion", "Infrastructure strain"],
  },
]

export const getAllDistricts = () => tamilNaduDistricts.map((d) => d.name)

export const getDistrictProfile = (districtName: string) => tamilNaduDistricts.find((d) => d.name === districtName)
