import type { DistrictProfile } from "./types"

export const tamilNaduDistricts: DistrictProfile[] = [
  {
    name: "Chennai",
    population: 4646732,
    ruralPopulation: 185000,
    totalHouseholds: 1200000,
    description: "Capital city and major metropolitan area of Tamil Nadu",
    keyIndustries: ["IT Services", "Automobile", "Healthcare", "Port Operations"],
    challenges: ["Limited rural areas", "Urban migration", "Infrastructure strain"],
  },
  {
    name: "Coimbatore",
    population: 3458045,
    ruralPopulation: 1200000,
    totalHouseholds: 850000,
    description: "Major industrial and textile hub known as the Manchester of South India",
    keyIndustries: ["Textiles", "Engineering", "Agriculture", "IT"],
    challenges: ["Water scarcity", "Industrial pollution", "Seasonal employment"],
  },
  {
    name: "Madurai",
    population: 3038252,
    ruralPopulation: 1800000,
    totalHouseholds: 750000,
    description: "Historic temple city and cultural center of Tamil Nadu",
    keyIndustries: ["Agriculture", "Handloom", "Tourism", "Small Scale Industries"],
    challenges: ["Agricultural dependency", "Drought conditions", "Rural unemployment"],
  },
  {
    name: "Tiruchirappalli",
    population: 2722290,
    ruralPopulation: 1600000,
    totalHouseholds: 680000,
    description: "Central Tamil Nadu district known for engineering and education",
    keyIndustries: ["Engineering", "Agriculture", "Education", "Heavy Industries"],
    challenges: ["Seasonal agriculture", "Water management", "Rural-urban divide"],
  },
  {
    name: "Salem",
    population: 3482056,
    ruralPopulation: 2100000,
    totalHouseholds: 870000,
    description: "Steel city and major agricultural center",
    keyIndustries: ["Steel", "Textiles", "Agriculture", "Sago"],
    challenges: ["Industrial pollution", "Agricultural distress", "Employment generation"],
  },
  {
    name: "Tirunelveli",
    population: 3077233,
    ruralPopulation: 2200000,
    totalHouseholds: 770000,
    description: "Southernmost district known for agriculture and traditional industries",
    keyIndustries: ["Agriculture", "Handloom", "Small Industries", "Tourism"],
    challenges: ["Monsoon dependency", "Traditional industry decline", "Youth migration"],
  },
  {
    name: "Vellore",
    population: 3936331,
    ruralPopulation: 2800000,
    totalHouseholds: 980000,
    description: "Leather and healthcare hub with significant rural population",
    keyIndustries: ["Leather", "Healthcare", "Agriculture", "Education"],
    challenges: ["Groundwater depletion", "Leather industry pollution", "Rural poverty"],
  },
  {
    name: "Erode",
    population: 2251744,
    ruralPopulation: 1400000,
    totalHouseholds: 560000,
    description: "Textile and turmeric trading center",
    keyIndustries: ["Textiles", "Agriculture", "Turmeric Trade", "Handloom"],
    challenges: ["Water scarcity", "Textile industry fluctuations", "Agricultural sustainability"],
  },
  {
    name: "Tiruppur",
    population: 2479052,
    ruralPopulation: 800000,
    totalHouseholds: 620000,
    description: "Knitwear capital of India",
    keyIndustries: ["Knitwear", "Textiles", "Garment Export", "Dyeing"],
    challenges: ["Water pollution", "Seasonal employment", "Export market dependency"],
  },
  {
    name: "Dindigul",
    population: 2159775,
    ruralPopulation: 1600000,
    totalHouseholds: 540000,
    description: "Lock and leather goods manufacturing center",
    keyIndustries: ["Lock Manufacturing", "Leather", "Agriculture", "Tanneries"],
    challenges: ["Traditional industry modernization", "Agricultural productivity", "Skill development"],
  },
  {
    name: "Thanjavur",
    population: 2405890,
    ruralPopulation: 1900000,
    totalHouseholds: 600000,
    description: "Rice bowl of Tamil Nadu and cultural heritage center",
    keyIndustries: ["Agriculture", "Rice Milling", "Handicrafts", "Tourism"],
    challenges: ["Monsoon dependency", "Agricultural modernization", "Cultural preservation"],
  },
  {
    name: "Nagapattinam",
    population: 1616450,
    ruralPopulation: 1400000,
    totalHouseholds: 400000,
    description: "Coastal district known for agriculture and fishing",
    keyIndustries: ["Agriculture", "Fishing", "Salt Production", "Port Activities"],
    challenges: ["Cyclone vulnerability", "Sea level rise", "Fishing industry sustainability"],
  },
  {
    name: "Cuddalore",
    population: 2605914,
    ruralPopulation: 1800000,
    totalHouseholds: 650000,
    description: "Industrial and port district on the east coast",
    keyIndustries: ["Petrochemicals", "Port Operations", "Agriculture", "Fishing"],
    challenges: ["Industrial pollution", "Coastal erosion", "Environmental degradation"],
  },
  {
    name: "Villupuram",
    population: 3458873,
    ruralPopulation: 2800000,
    totalHouseholds: 860000,
    description: "Predominantly agricultural district with high rural population",
    keyIndustries: ["Agriculture", "Rice Milling", "Handloom", "Small Industries"],
    challenges: ["Agricultural dependency", "Rural unemployment", "Infrastructure development"],
  },
  {
    name: "Kanchipuram",
    population: 3998252,
    ruralPopulation: 2200000,
    totalHouseholds: 1000000,
    description: "Silk saree weaving center and temple town",
    keyIndustries: ["Silk Weaving", "Agriculture", "Tourism", "Handloom"],
    challenges: ["Traditional industry competition", "Urbanization pressure", "Skill preservation"],
  },
  {
    name: "Tiruvallur",
    population: 3728104,
    ruralPopulation: 2000000,
    totalHouseholds: 930000,
    description: "Rapidly developing district near Chennai",
    keyIndustries: ["Agriculture", "Small Industries", "IT", "Manufacturing"],
    challenges: ["Urban expansion", "Agricultural land conversion", "Infrastructure strain"],
  },
  {
    name: "Ariyalur",
    population: 752481,
    ruralPopulation: 640000,
    totalHouseholds: 190000,
    description: "Agricultural district known for limestone and cement industries",
    keyIndustries: ["Cement", "Agriculture", "Limestone Mining", "Small Industries"],
    challenges: ["Mining pollution", "Agricultural productivity", "Water scarcity"],
  },
  {
    name: "Chengalpattu",
    population: 2559007,
    ruralPopulation: 1280000,
    totalHouseholds: 640000,
    description: "Newly formed district with mix of urban and rural areas",
    keyIndustries: ["Agriculture", "IT", "Manufacturing", "Services"],
    challenges: ["Urbanization", "Infrastructure development", "Employment opportunities"],
  },
  {
    name: "Dharmapuri",
    population: 1506843,
    ruralPopulation: 1235000,
    totalHouseholds: 380000,
    description: "Predominantly rural district with agricultural focus",
    keyIndustries: ["Agriculture", "Mango Cultivation", "Dairy", "Handloom"],
    challenges: ["Drought conditions", "Low irrigation", "Rural unemployment"],
  },
  {
    name: "Kallakurichi",
    population: 1367538,
    ruralPopulation: 1067000,
    totalHouseholds: 340000,
    description: "Newly formed district with agricultural economy",
    keyIndustries: ["Agriculture", "Rice Cultivation", "Handloom", "Small Industries"],
    challenges: ["Agricultural dependency", "Water management", "Infrastructure gaps"],
  },
  {
    name: "Kanniyakumari",
    population: 1863014,
    ruralPopulation: 840000,
    totalHouseholds: 460000,
    description: "Southernmost district known for tourism and fishing",
    keyIndustries: ["Tourism", "Fishing", "Agriculture", "Rubber Plantation"],
    challenges: ["Coastal erosion", "Tourism seasonality", "Fishing sustainability"],
  },
  {
    name: "Karur",
    population: 1076626,
    ruralPopulation: 700000,
    totalHouseholds: 270000,
    description: "Textile and handloom center",
    keyIndustries: ["Handloom", "Textiles", "Agriculture", "Banking"],
    challenges: ["Traditional industry competition", "Market fluctuations", "Skill development"],
  },
  {
    name: "Krishnagiri",
    population: 1879809,
    ruralPopulation: 1316000,
    totalHouseholds: 470000,
    description: "Fruit and vegetable producing district",
    keyIndustries: ["Horticulture", "Agriculture", "Mango Production", "Dairy"],
    challenges: ["Water scarcity", "Market access", "Cold storage facilities"],
  },
  {
    name: "Mayiladuthurai",
    population: 917356,
    ruralPopulation: 734000,
    totalHouseholds: 230000,
    description: "Newly formed district with agricultural and cultural heritage",
    keyIndustries: ["Agriculture", "Rice Cultivation", "Tourism", "Handloom"],
    challenges: ["Monsoon dependency", "Cultural preservation", "Rural development"],
  },
  {
    name: "Namakkal",
    population: 1726601,
    ruralPopulation: 1174000,
    totalHouseholds: 430000,
    description: "Poultry and transport hub",
    keyIndustries: ["Poultry", "Transport", "Agriculture", "Textiles"],
    challenges: ["Disease management", "Market volatility", "Transport infrastructure"],
  },
  {
    name: "Nilgiris",
    population: 735394,
    ruralPopulation: 441000,
    totalHouseholds: 180000,
    description: "Hill station district known for tea plantations and tourism",
    keyIndustries: ["Tourism", "Tea Plantation", "Horticulture", "Forestry"],
    challenges: ["Environmental conservation", "Tourism seasonality", "Climate change"],
  },
  {
    name: "Perambalur",
    population: 565223,
    ruralPopulation: 486000,
    totalHouseholds: 140000,
    description: "Small agricultural district",
    keyIndustries: ["Agriculture", "Rice Cultivation", "Small Industries", "Handloom"],
    challenges: ["Limited industries", "Agricultural dependency", "Employment generation"],
  },
  {
    name: "Pudukkottai",
    population: 1617525,
    ruralPopulation: 1245000,
    totalHouseholds: 400000,
    description: "Historical district with agricultural economy",
    keyIndustries: ["Agriculture", "Rice Milling", "Handloom", "Small Industries"],
    challenges: ["Monsoon dependency", "Low industrialization", "Rural unemployment"],
  },
  {
    name: "Ramanathapuram",
    population: 1353445,
    ruralPopulation: 1015000,
    totalHouseholds: 340000,
    description: "Coastal district with fishing and agriculture",
    keyIndustries: ["Fishing", "Agriculture", "Salt Production", "Tourism"],
    challenges: ["Coastal erosion", "Cyclone vulnerability", "Fishing sustainability"],
  },
  {
    name: "Ranipet",
    population: 1206227,
    ruralPopulation: 844000,
    totalHouseholds: 300000,
    description: "Newly formed district with industrial potential",
    keyIndustries: ["Leather", "Agriculture", "Small Industries", "Services"],
    challenges: ["Industrial development", "Infrastructure", "Employment opportunities"],
  },
  {
    name: "Sivagangai",
    population: 1339101,
    ruralPopulation: 1044000,
    totalHouseholds: 330000,
    description: "Agricultural district with cultural significance",
    keyIndustries: ["Agriculture", "Rice Cultivation", "Handloom", "Small Industries"],
    challenges: ["Agricultural dependency", "Water management", "Rural development"],
  },
  {
    name: "Tenkasi",
    population: 1407957,
    ruralPopulation: 1056000,
    totalHouseholds: 350000,
    description: "Newly formed district in southern Tamil Nadu",
    keyIndustries: ["Agriculture", "Handloom", "Small Industries", "Tourism"],
    challenges: ["Infrastructure development", "Employment generation", "Water resources"],
  },
  {
    name: "Theni",
    population: 1243091,
    ruralPopulation: 870000,
    totalHouseholds: 310000,
    description: "Fruit and cardamom producing district",
    keyIndustries: ["Horticulture", "Cardamom", "Agriculture", "Textiles"],
    challenges: ["Market price fluctuations", "Water management", "Climate variability"],
  },
  {
    name: "Thoothukudi",
    population: 1750206,
    ruralPopulation: 1138000,
    totalHouseholds: 440000,
    description: "Port city and industrial district",
    keyIndustries: ["Port Operations", "Salt Production", "Fishing", "Industries"],
    challenges: ["Industrial pollution", "Coastal erosion", "Employment generation"],
  },
  {
    name: "Tirupathur",
    population: 1103459,
    ruralPopulation: 794000,
    totalHouseholds: 280000,
    description: "Newly formed district with agricultural base",
    keyIndustries: ["Agriculture", "Textiles", "Small Industries", "Handloom"],
    challenges: ["Infrastructure development", "Employment opportunities", "Water resources"],
  },
  {
    name: "Tiruvannamalai",
    population: 2464870,
    ruralPopulation: 1849000,
    totalHouseholds: 620000,
    description: "Spiritual and agricultural district",
    keyIndustries: ["Tourism", "Agriculture", "Rice Cultivation", "Handloom"],
    challenges: ["Tourism infrastructure", "Agricultural productivity", "Water management"],
  },
  {
    name: "Tiruvarur",
    population: 1264277,
    ruralPopulation: 1037000,
    totalHouseholds: 320000,
    description: "Agricultural district with cultural heritage",
    keyIndustries: ["Agriculture", "Rice Cultivation", "Tourism", "Handloom"],
    challenges: ["Monsoon dependency", "Cultural preservation", "Rural development"],
  },
  {
    name: "Virudhunagar",
    population: 1942288,
    ruralPopulation: 1360000,
    totalHouseholds: 480000,
    description: "Agricultural and industrial district",
    keyIndustries: ["Agriculture", "Textiles", "Fireworks", "Match Industries"],
    challenges: ["Industrial safety", "Agricultural productivity", "Employment generation"],
  },
]

export const getAllDistricts = () => tamilNaduDistricts.map((d) => d.name)

export const getDistrictProfile = (districtName: string) => tamilNaduDistricts.find((d) => d.name === districtName)
